# Generated by Django 4.1.5 on 2023-01-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iphone14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('version', models.TextField(default='')),
                ('maincamera', models.TextField(default='')),
                ('rearcamera', models.TextField(default='')),
                ('battery', models.TextField(default='')),
                ('display', models.TextField(default='')),
                ('memory', models.TextField(default='')),
            ],
        ),
    ]
